v1-f1
fire567/carsharingV2 pull request #1
Opened 2022-03-15 18:25 UTC by fire567

2022-03-17 05:12 UTC, EvgeniyaFilatova commented
Десктоп: сделай так, чтобы сбоку выезжало только меню (отметила красной рамкой). Остальное - это оверлей, он не должен выезжать, а просто накладываться на контент
![image](https://user-images.githubusercontent.com/90593835/158741577-c4a467a3-4543-40d4-a12c-12f8a6fd4dd9.png)

2022-03-17 05:56 UTC, EvgeniyaFilatova requested changes

2022-03-17 05:56 UTC, EvgeniyaFilatova commented on public/index.html
> +  <body style="margin: 0">
- [ ] Не используй инлайн стили, перенеси куда-то в src/

2022-03-17 05:56 UTC, EvgeniyaFilatova commented on src/App.css
> +  font-family: "Roboto-Regular";
- [ ] Давай лучше для всех шрифтов сделаем одно название, то есть Roboto, но для всех еще пропишешь font-weight и будешь указывать дополнительно это свойство при использовании шрифта. Пример:
![image](https://user-images.githubusercontent.com/90593835/158742909-6c7c2a04-3c66-4848-bfa7-f030b18f7625.png)

2022-03-17 05:56 UTC, EvgeniyaFilatova commented on src/App.js
> +function App({isMenuOpened}) {
- [ ] Используй новый синтаксис, стрелочные функции

2022-03-17 05:56 UTC, EvgeniyaFilatova commented on src/App.js
> +const mapStateToProps = (state) => {
- [ ] Используй хуки из пакета react-redux, в данном случае useSelector. Но нужна ли тебе здесь данная переменная вообще? Она не используется в компоненте

2022-03-17 05:56 UTC, EvgeniyaFilatova commented on src/Components/Carousel/Carousel.js
> +        direction === "right" ?  setCurrentSlide(
Возможные значения direction лучше убрать в константы, можно использовать объект или enum. Ну или просто использовать одно константное значение, например, RIGHT_DIRECTION = 'right'

2022-03-17 05:56 UTC, EvgeniyaFilatova commented on src/Components/Carousel/Carousel.js
> +        {id:0, pos: 0},
Почему именно шаг 100?

2022-03-17 05:56 UTC, EvgeniyaFilatova commented on src/Components/Carousel/Carousel.js
> +                <div className="left-arrow"></div>
- [ ] Используй самозакрывающийся тег

2022-03-17 05:56 UTC, EvgeniyaFilatova commented on src/Components/Carousel/Slides/Slides.js
> +    const carouselItems = [
- [ ] Вынеси это в отдельный файл с константами в этой же папке, чтобы не захламлять сам компонент

2022-03-17 05:56 UTC, EvgeniyaFilatova commented on src/Components/MainPageContent/MainPageContent.js
> +import "./MainPageContent.css";
Используй для стилизации css модули

2022-03-17 05:56 UTC, EvgeniyaFilatova commented on src/Components/MainPageContent/MainPageContent.js
> +                <div className="main-page-content">
- [ ] Старайся по проекту использовать семантические теги, где есть возможность

2022-03-17 05:56 UTC, EvgeniyaFilatova commented on src/Components/Menu/Menu.js
> +        <div className={isMenuOpened === true ? "menu-form" : "menu-form-closed"}>
- [ ] Здесь можно убрать строгое сравнение - будет то же самое, так как выражение до ? будет автоматически преобразовано в булевое значение

2022-03-17 05:56 UTC, EvgeniyaFilatova commented on src/Components/Menu/Menu.js
> +export default connect(mapStateToProps, {
- [ ] Использовать хуки, UseDispatch

2022-03-17 05:56 UTC, EvgeniyaFilatova commented on src/Components/Menu/Menu.js
> +        isMenuOpened: state.isMenuOpened,
- [ ] Зачем хранить это в стейт менеджере? Это же просто состояние меню, можно вынести в стейт компонента

2022-03-17 05:56 UTC, EvgeniyaFilatova commented on src/Components/Sidebar/Sidebar.js
> +const mapStateToProps = (state) => {
- [ ] Хуки

2022-03-17 05:56 UTC, EvgeniyaFilatova commented on src/index.js
> +  <HashRouter basename={process.env.PUBLIC_URL}>
Лучше роутинг перенести в App.js как раз, обычно такая структура

2022-03-17 06:05 UTC, EvgeniyaFilatova commented
- [ ] По файловой структуре проекта еще посмотри какие-нибудь статьи в интернете. По стейт менеджеру лучше всё в одну общую папку убрать (экшены, редьюсеры). Компонент MainPageContent по логике не должен быть в Components, скорее в Pages. Если правильно поняла логику, то в Components ты хочешь хранить UI-компоненты, которые могут быть переиспользованы во многих частях приложения. Так у тебя в принципе неплохо со структурой

2022-03-17 07:14 UTC, fire567 commented on src/Components/Carousel/Carousel.js
> +        direction === "right" ?  setCurrentSlide(
![qwe](https://user-images.githubusercontent.com/34776934/158756132-5c5ea933-7097-4f45-a7cb-1634efbb9a2b.PNG)

2022-03-17 07:14 UTC, fire567 commented on src/Components/Carousel/Carousel.js
> +        direction === "right" ?  setCurrentSlide(
Вот так имеешь ввиду?

2022-03-17 07:24 UTC, fire567 commented on src/Components/Menu/Menu.js
> +        isMenuOpened: state.isMenuOpened,
Имеешь ввиду хранение этого стейта в стейт менеджере в принципе не обязательно или только в этом компоненте?

2022-03-17 07:58 UTC, EvgeniyaFilatova commented on src/Components/Carousel/Carousel.js
> +        direction === "right" ?  setCurrentSlide(
Да, и можно вынести эту константу в какой-то общий файл consts для приложения

2022-03-17 08:10 UTC, EvgeniyaFilatova commented on src/Components/Menu/Menu.js
> +        isMenuOpened: state.isMenuOpened,
В принципе не вижу смысла хранить данную информацию для меню в редаксе. Можешь поискать решения по меню в интернете. Например, вот есть реализация: https://codesandbox.io/s/modest-euclid-m5gyq?from-embed

2022-03-17 08:24 UTC, fire567 commented on src/Components/Menu/Menu.js
> +        isMenuOpened: state.isMenuOpened,
Просто мне всё равно же придётся передавать информацию стейта с одного компонента в другой. Компонент Sidebar передаёт компоненту Menu информацию о том что надо появиться на экране

2022-03-17 12:06 UTC, EvgeniyaFilatova commented on src/Components/Menu/Menu.js
> +        isMenuOpened: state.isMenuOpened,
Если есть необходимость передавать информацию, то ты можешь стейт вынести как раз в родительский элемент, а менять его состояние в дочернем, передавая нужные переменные через пропсы. Опять же, посмотри даже ту реализацию, которую я тебе скинула. Там компонент "гамбургер" является дочерним, в него через пропсы передается значение стейта меню и функция для его изменения

2022-03-17 12:19 UTC, EvgeniyaFilatova commented on src/Components/Menu/Menu.js
> +        isMenuOpened: state.isMenuOpened,
Но посмотри в принципе подходы к реализации меню в приложениях. Скорее всего тебе нужно поменять реализацию свою будет

2022-03-17 15:35 UTC, fire567 commented on src/Components/Menu/Menu.js
> +        isMenuOpened: state.isMenuOpened,
Вроде всё исправил, можно перепроверять

2022-03-18 13:00 UTC, EvgeniyaFilatova commented
- [ ] При закрытии бокового меню сделай тоже анимацию, сейчас ее нет (есть только при открытии)

2022-03-18 13:33 UTC, EvgeniyaFilatova requested changes

2022-03-18 13:33 UTC, EvgeniyaFilatova commented on src/App.js
> +  console.log(isOpened)
- [ ] Не забывай удалять отладочный код. Настрой eslint, который будет за этим следить (дополнительно в vscode, например, можно добавить плагин, который будет подсвечивать ошибки)

2022-03-18 13:33 UTC, EvgeniyaFilatova commented on src/Components/Carousel/Carousel.js
> +                <div className="left-arrow"></div>
- [ ] Не исправлено

2022-03-18 13:33 UTC, EvgeniyaFilatova commented on src/Components/Carousel/Slides/Slides.js
> +    const carouselItems = [
- [ ] Не исправлено

2022-03-18 13:33 UTC, EvgeniyaFilatova commented on src/Pages/MainPage/MainPageContent/MainPageContent.js
> +import "./MainPageContent.css";
- [ ] Используй css модули во всем проекте

2022-03-18 14:06 UTC, fire567 commented on src/Pages/MainPage/MainPageContent/MainPageContent.js
> +import "./MainPageContent.css";
Не совсем понимаю что в компоненте Slides не правильно

2022-03-22 06:10 UTC, EvgeniyaFilatova commented on src/Components/Sidebar/Sidebar.js
> +                    {language === true ? "Рус" : "Eng"}
Опять же, будет преобразовано к булевому значению, то есть можно просто оставить language ? "Рус" : "Eng"
И лучше делать более осмысленное название, у тебя стейт отвечает именно за то, является ли язык русским или нет, было бы лучше назвать тогда isRussianLanguage

2022-03-22 06:13 UTC, EvgeniyaFilatova commented on src/Components/Carousel/Carousel.js
> +                <div className={classes.left_arrow}></div>
Используй самозакрывающийся тег, если внутри не передаешь children
То есть эта строка должна быть вот такой <div className={classes.left_arrow} **/>**

2022-03-22 06:15 UTC, EvgeniyaFilatova commented on src/Redux/actions/index.js
> +export const setLanguage = (language) => {
Вроде теперь тебе в сторе не нужны ни язык, ни состояние меню. Удали тогда

2022-03-22 11:14 UTC, merged