F3/v4
fire567/carsharingV2 pull request #4
Opened 2022-03-28 11:07 UTC by fire567

2022-03-29 08:23 UTC, EvgeniyaFilatova commented
- [ ] Есть некоторые изображения, которые залезают на информацию об автомобиле, необходимо ограничить картинку по высоте и ширине
![image](https://user-images.githubusercontent.com/90593835/160567201-8b2fe55c-5d59-4614-acc9-5c2944fff1c9.png)

2022-03-29 08:35 UTC, EvgeniyaFilatova commented
- [ ] На планшете и мобильном разрешении думаю стоит еще немножко поработать над макетом. Сейчас получается, что кнопка для продолжения оформления находится в попапе, который открывается при нажатии на иконку внизу экрана. Мне кажется, что со стороны UX это не очень хорошо, пользователь может растеряться и не понять, какие действия для перехода на следующий шаг нужно совершить. Наверное самое простое - это вынести кнопку на главный лейаут, чтобы пользователь сразу ее видел. Но тут тогда будет проблема на втором шаге, так как там бесконечный скролл для всех машин, и если кнопка будет снизу, то пользователь до нее не долистает. Можно тогда либо выносить эту кнопку наверх, до списка, либо переделать само отображение списка - добавить пагинацию. Можешь реализовать любой вариант, какой тебе нравится, либо предложить свой
![image](https://user-images.githubusercontent.com/90593835/160569429-ee9c9c76-6d1e-412e-a05d-866e2fb72154.png)

2022-03-29 08:41 UTC, EvgeniyaFilatova commented
- [ ] Настрой еще prettier для проекта

2022-03-29 08:58 UTC, EvgeniyaFilatova requested changes

2022-03-29 08:58 UTC, EvgeniyaFilatova commented on src/Components/CarsList/CarsList.module.css
> +.car_form_active{
- [ ] У тебя получается стили для активного состояния и обычно во многом дублируют друг друга. Вынеси в класс обычного состояния все те стили, которые у них пересекаются, а для активного класса только добавь те, что меняются при активном состоянии. И тогда в самом компоненте немного поменяется условие для className: в нем всегда будет присутствовать базовый класс и добавляться активный при определенном условии (для формирования имени класса используй пакет classsnames)
- [ ] Пройдись по всему проекту и порефачь этот момент везде

2022-03-29 08:58 UTC, EvgeniyaFilatova commented on src/Components/Loading/Loading.js
> +      <div className={classes.img} style={{ backgroundImage: `url(${loading})` }} />
- [ ] Почему через инлайн-стили? Можно в файл со стилями убрать

2022-03-29 08:58 UTC, EvgeniyaFilatova commented on src/Components/OrderInf/OrderInf.js
> +        item: location && location,
- [ ] Зачем здесь логический оператор? Он не играет никакой роли

2022-03-29 08:58 UTC, EvgeniyaFilatova commented on src/Components/OrderInf/OrderInf.js
> +        item: currentCar && currentCar,
- [ ] Аналогично

2022-03-29 08:58 UTC, EvgeniyaFilatova commented on src/Components/OrderInfMobile/OrderInfMobile.js
> +                    {infArr
- [ ] Мне кажется, что у тебя основная часть этого компонента дублирует компонент OrderInf. Почему бы просто тогда не импортить этот компонент сюда и использовать?

2022-03-29 08:58 UTC, EvgeniyaFilatova commented on src/Pages/OrderPage/OrderPage.js
> +  window.onload = () => {
- [ ] Для чего здесь переброс на главную страницу при загрузке страницы?

2022-03-29 09:40 UTC, fire567 commented on src/Pages/OrderPage/OrderPage.js
> +  window.onload = () => {
При обновлени  страницы будут слетать все стейты оформления. Подумал пусть тогда пользователя перебрасывает в начало чтобы он заново начинал оформление

2022-03-29 10:18 UTC, EvgeniyaFilatova commented on src/Pages/OrderPage/OrderPage.js
> +  window.onload = () => {
Может, тогда перебрасывать на первый этап оформления сразу, на выбор пункта выдачи?

2022-03-29 10:20 UTC, fire567 commented on src/Pages/OrderPage/OrderPage.js
> +  window.onload = () => {
Да, давай так и сделаю

2022-03-30 12:25 UTC, EvgeniyaFilatova commented
- [ ] Теперь получается, что ты загружаешь только первые 10 автомобилей и всё, больше у тебя на странице не подгружаются остальные данные. А их всего где-то около 80 штук сейчас. Используй еще параметр page (если page=1, то берутся первые 10 машин, page=2, следующие 10 и так далее). И возможно тогда стоит на десктопе тоже сделать пагинацию

2022-03-30 12:27 UTC, EvgeniyaFilatova commented
- [ ] Кнопку перехода из поапа можно убрать тогда, если ты ее перенес
![image](https://user-images.githubusercontent.com/90593835/160834105-b90784c1-ee75-4651-bddb-024bb8e61924.png)

2022-03-30 12:29 UTC, EvgeniyaFilatova commented
- [ ] Можно на мобильном разрешении по два-три автомобиля выводить
![image](https://user-images.githubusercontent.com/90593835/160834680-92e54d88-51be-4081-a6f5-8b1023b75636.png)

2022-03-30 12:39 UTC, EvgeniyaFilatova commented
- [ ] Блок с машинами прям совсем мелкий по высоте получается. Давай сделаем лучше такой вариант: ты сейчас ограничил высоту блока с машинами, чтобы кнопка всегда была внизу экрана. Можно убрать это ограничение по высоте, будет выводиться по три машины в столбик, а кнопку сделать position: fixed внизу экрана, будет за скроллом страницы ездить
![image](https://user-images.githubusercontent.com/90593835/160836189-ebbbb6c0-5159-49ae-99f8-30d26e3d3f0e.png)

2022-03-30 12:41 UTC, EvgeniyaFilatova commented
- [ ] Не настроил prettier, настрой

2022-03-30 12:58 UTC, EvgeniyaFilatova requested changes

2022-03-30 12:58 UTC, EvgeniyaFilatova commented on src/Components/CarsList/CarsList.js
> +        [classes.car_form]: true,
- [ ] Просто classes.car_form, здесь условие не нужно, оно же всегда true

2022-03-30 12:58 UTC, EvgeniyaFilatova commented on src/Components/CarsList/CarsList.js
> +        [classes.car_form_unactive]: currentCar && currentCar.id !== car.id,
- [ ] Зачем вообще класс classes.car_form_unactive? У тебя он опять дублирует уже то, что есть в classes.car_form. Он здесь не нужен

2022-03-30 12:58 UTC, EvgeniyaFilatova commented on src/Components/LocationInput/LocationInput.js
> +        ></input>
- [ ] Самозакрывающийся тег используй. Вроде eslint можно настроить на подобное

2022-03-30 12:58 UTC, EvgeniyaFilatova commented on src/Components/OrderInf/OrderInf.js
> +          <div className={classes.order_inf_header}>Ваш заказ:</div>
- [ ] У тебя же опять получается дублирование. Смысл был в том, чтобы выделить вот этот блок со скрина как самостоятельный компонент и использовать его в нескольких местах
![image](https://user-images.githubusercontent.com/90593835/160839418-e1b189e7-8b60-4d38-a90d-824112db6973.png)

2022-04-01 11:53 UTC, EvgeniyaFilatova requested changes

2022-04-01 11:53 UTC, EvgeniyaFilatova commented on .vscode/settings.json
> +{
- [x] Добавь в гитигнор файл

2022-04-01 11:57 UTC, EvgeniyaFilatova commented
- [ ] Еще нужно доработать планшетную версию, сейчас она не очень смотрится. Во-первых, хочется, чтобы побольше машин отображалось, чем на мобильной версии, планшет это позволяет. Во-вторых, думаю, на планшете можно фильтр не убирать в боковую панель, опять же места предостаточно, оставляй как на десктопе, а на мобильном разрешении убирай, как у тебя есть сейчас
![image](https://user-images.githubusercontent.com/90593835/161258834-94632e90-f960-4769-a8a3-e3d0c0bc80bd.png)

2022-04-01 15:25 UTC, merged